const colors = {
  light: {
    text: "#09090B",
    tint: "#FF4458",
    background: "#F4F4F5",
    foreground: "#09090B",
    card: "#FFFFFF",
    cardForeground: "#09090B",
    primary: "#FF4458",
    primaryForeground: "#FFFFFF",
    secondary: "#F4F4F5",
    secondaryForeground: "#09090B",
    muted: "#F4F4F5",
    mutedForeground: "#71717A",
    accent: "#7C3AED",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E4E4E7",
    input: "#E4E4E7",
    success: "#22C55E",
  },
  dark: {
    text: "#FAFAFA",
    tint: "#FF4458",
    background: "#09090B",
    foreground: "#FAFAFA",
    card: "#18181B",
    cardForeground: "#FAFAFA",
    primary: "#FF4458",
    primaryForeground: "#FFFFFF",
    secondary: "#27272A",
    secondaryForeground: "#FAFAFA",
    muted: "#27272A",
    mutedForeground: "#A1A1AA",
    accent: "#7C3AED",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#27272A",
    input: "#27272A",
    success: "#22C55E",
  },
  radius: 14,
};

export default colors;
