const colors = {
  light: {
    text: "#09090B",
    tint: "#FF4D6D",
    background: "#F4F4F5",
    foreground: "#09090B",
    card: "#FFFFFF",
    cardForeground: "#09090B",
    primary: "#FF4D6D",
    primaryForeground: "#FFFFFF",
    secondary: "#F4F4F5",
    secondaryForeground: "#09090B",
    muted: "#F4F4F5",
    mutedForeground: "#71717A",
    accent: "#FF4D6D",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E4E4E7",
    input: "#E4E4E7",
    success: "#22C55E",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#FF4D6D",
    background: "#0B0B0F",
    foreground: "#FFFFFF",
    card: "#15151C",
    cardForeground: "#FFFFFF",
    primary: "#FF4D6D",
    primaryForeground: "#FFFFFF",
    secondary: "#2A2A35",
    secondaryForeground: "#FFFFFF",
    muted: "#2A2A35",
    mutedForeground: "#A1A1AA",
    accent: "#FF4D6D",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A35",
    input: "#2A2A35",
    success: "#22C55E",
  },
  radius: 14,
};

export default colors;
